#!/usr/bin/env python3
# The CSV Cleaner
# Weston Spiro 2023
import tkinter as tk
from tkinter import filedialog, messagebox
import csv

def clean_file(input_file):
    output_file = input_file[:-4] + "Cleaned.csv"
    with open(input_file, 'r', newline='') as f_in, open(output_file, 'w', newline='') as f_out:
        reader = csv.reader(f_in)
        writer = csv.writer(f_out)
        for row in reader:
            new_row = []
            for cell in row:
                new_cell = ""
                for char in cell:
                    if char not in ['!', '@', '#', '^', '&', '*', '(', ')', '[', ']', '{', '}', '~', '`', "'", ':', ';', '<', '>', '/', '\\', '_', '|', '"', '?']:
                        new_cell += char
                new_row.append(new_cell)
            writer.writerow(new_row)
    return output_file

def browse_file():
    file_path = filedialog.askopenfilename()
    if file_path:
        cleaned_file = clean_file(file_path)
        file_name = file_path.split("/")[-1]
        messagebox.showinfo(title="Success", message=f"{file_name} \ncleaned successfully \nand saved as \n{cleaned_file}")

root = tk.Tk()
root.title("The_CSV_Cleaner")

browse_button = tk.Button(root, text="Select CSV file", command=browse_file)
browse_button.pack()

quit_button = tk.Button(root, text = "Quit", command=root.destroy)
quit_button.pack()

label_text = "The CSV Cleaner \nWeston Spiro 2023"
label = tk.Label(root, text=label_text)
label.pack()

root.mainloop()
